spring.application.name=orm_exercises

spring.datasource.url=jdbc:mysql://localhost:3306/orm-exercises?useSSL=false
spring.datasource.username=root
spring.datasource.password=leM!pump7ySQL
spring.jpa.hibernate.ddl-auto=update